In [1]:
import math
import numpy as np
import h5py
from PIL import Image
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset,random_mini_batches,convert_to_one_hot,predict

%matplotlib inline
np.random.seed(1)

In [2]:
y_hat=tf.constant(36,name='y_hat')
y=tf.constant(39,name='y')

loss=tf.Variable((y-y_hat)**2,name='loss')

init=tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print(session.run(loss))

9


In [3]:
a=tf.constant(2)
b=tf.constant(10)
c=tf.multiply(a,b)
print(c)

Tensor("Mul:0", shape=(), dtype=int32)


In [4]:
sess=tf.Session()
print(sess.run(c))

20


In [5]:
x=tf.placeholder(tf.int64,name='x')
print(sess.run(2*x,feed_dict={x:3}))
sess.close()

6


In [6]:
def linear_function():
    
    np.random.seed(1)
    
    X = np.random.randn(3, 1)
    W = np.random.randn(4, 3)
    b = np.random.randn(4, 1)
    Y = tf.add(tf.matmul(W, X), b)

    sess = tf.Session()
    result = sess.run(Y)

    sess.close()

    return result

In [7]:
print("result = "+str(linear_function()))

result = [[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


In [8]:
def sigmoid(z):
    x=tf.placeholder(tf.float32,name="x")
    
    sigmoid=tf.sigmoid(x)
    
    with tf.Session() as sess:
        result=sess.run(sigmoid,feed_dict={x:z})
    return result

In [9]:
print("sigmoid(0) = "+str(sigmoid(0)))
print("sigmoid(12) = "+str(sigmoid(12)))

sigmoid(0) = 0.5
sigmoid(12) = 0.9999938


In [10]:
def cost(logits,labels):
    z=tf.placeholder(tf.float32,name="z")
    y=tf.placeholder(tf.float32,name="y")
    
    cost=tf.nn.sigmoid_cross_entropy_with_logits(logits=z,labels=y)
    
    sess=tf.Session()
    
    cost=sess.run(cost,feed_dict={z:logits,y:labels})
    
    sess.close()
    
    return cost

In [11]:
logits=sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost=cost(logits,np.array([0,0,1,1]))
print("cost = "+str(cost))

W0907 00:42:07.595829  1636 deprecation.py:323] From C:\Users\Hrishikesh D S\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


cost = [1.0053873  1.0366408  0.41385433 0.39956617]


In [12]:
def one_hot_matrix(labels,C):
    C=tf.constant(C,name='C')
    one_hot_matrix=tf.one_hot(indices=labels,depth=C,axis=0)
    sess=tf.Session()
    one_hot=sess.run(one_hot_matrix)
    sess.close()
    return one_hot

In [13]:
labels=np.array([1,2,3,0,2,1])
one_hot=one_hot_matrix(labels,C=4)
print("one_hot = "+str(one_hot))

one_hot = [[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [14]:
def ones(shape):
    ones=tf.ones(shape)
    sess=tf.Session()
    ones=sess.run(ones)
    sess.close()
    return ones

In [15]:
print("ones = "+str(ones([3])))

ones = [1. 1. 1.]
